'''
This module contains some constants that are used by the Bluetooth Low Energy stack.
'''

TYPE_HCI_COMMAND		= 0x1
TYPE_ACL_DATA 			= 0x2
TYPE_HCI_EVENT 			= 0x4

HCI_LE_META  			= 0x3e

HCI_CONNECTION_COMPLETE 	= 0x1
HCI_ADVERTISING_REPORT 		= 0x2
HCI_LONG_TERM_KEY_REQUEST	= 0x5
HCI_ENCRYPTION_CHANGE 		= 0x8
HCI_ENHANCED_CONNECTION_COMPLETE= 0xa

HCI_DISCONNECTION_COMPLETE 	= 0x5

ADV_IND 			= 0x0
ADV_DIRECT_IND			= 0x1
ADV_SCAN_IND 			= 0x2
ADV_NONCONN_IND 		= 0x3
SCAN_RSP			= 0x4
ADV_DIRECT_IND_LOW		= 0x4

# ATT Error Codes
ATT_ERR_INVALID_HANDLE		=	0x01
ATT_ERR_READ_NOT_PERMITTED   	=	0x02
ATT_ERR_WRITE_NOT_PERMITTED   	=	0x03
ATT_ERR_INVALID_PDU   		=	0x04
ATT_ERR_INSUFFICIENT_AUTHEN	=	0x05
ATT_ERR_UNSUPPORTED_REQ   	=	0x06
ATT_ERR_INVALID_OFFSET   	=	0x07
ATT_ERR_INSUFFICIENT_AUTHOR	=	0x08
ATT_ERR_PREPARE_QUEUE_FULL   	=	0x09
ATT_ERR_ATTR_NOT_FOUND		=	0x0a
ATT_ERR_ATTR_NOT_LONG   	=	0x0b
ATT_ERR_INSUFFICIENT_KEY_SIZE	=	0x0c
ATT_ERR_INVALID_VALUE_SIZE   	=	0x0d
ATT_ERR_UNLIKELY   		=	0x0e
ATT_ERR_INSUFFICIENT_ENCRYPT	=	0x0f
ATT_ERR_UNSUPPORTED_GRP_TYPE   	=	0x10
ATT_ERR_INSUFFICIENT_RESOURCES	=	0x11
ATT_ERR_INVALID_VALUE   	=	0x80

# SM Error Codes
SM_ERR_PASSKEY_ENTRY_FAILED	=	0x01
SM_ERR_OOB_NOT_AVAILABLE	=	0x02
SM_ERR_AUTH_REQUIREMENTS	=	0x03
SM_ERR_CONFIRM_VALUE_FAILED	=	0x04
SM_ERR_PAIRING_NOT_SUPPORTED	=	0x05
SM_ERR_ENCRYPTION_KEY_SIZE	=	0x06
SM_ERR_COMMAND_NOT_SUPPORTED	=	0x07
SM_ERR_UNSPECIFIED_REASON	=	0x08
SM_ERR_REPEATED_ATTEMPTS	=	0x09
SM_ERR_INVALID_PARAMETERS	=	0x0A
SM_ERR_DHKEY_CHECK_FAILED	=	0x0B
SM_ERR_NUMERIC_COMPARISON_FAILED=	0x0C
SM_ERR_BREDR_PAIRING_IN_PROGRESS=	0x0D
SM_ERR_CROSS_TRANSPORT_KEY	=	0x0E


CONTROL_TYPES = {
0x00 : "LL_CONNECTION_UPDATE_REQ",
0x01 : "LL_CHANNEL_MAP_REQ",
0x02 : "LL_TERMINATE_IND",
0x03 : "LL_ENC_REQ",
0x04 : "LL_ENC_RSP",
0x05 : "LL_START_ENC_REQ",
0x06 : "LL_START_ENC_RESP",
0x07 : "LL_UNKNOWN_RSP",
0x08 : "LL_FEATURE_REQ",
0x09 : "LL_FEATURE_RSP",
0x0A : "LL_PAUSE_ENC_REQ",
0x0B : "LL_PAUSE_ENC_RSP",
0x0C : "LL_VERSION_IND",
0x0D : "LL_REJECT_IND"
}

ADV_TYPES = {
0: "ADV_IND",
1: "ADV_DIRECT_IND",
2: "ADV_NONCONN_IND",
3: "SCAN_REQ",
4: "SCAN_RSP",
5: "CONNECT_REQ",
6: "ADV_SCAN_IND"
}

# Enumeration for operation mode
class BLEOperationMode:
	NORMAL 		= 0x0
	SCANNING 	= 0x1
	ADVERTISING 	= 0x2

# Enumeration for sniffing mode
class BLESniffingMode:
	ADVERTISEMENT		= 0x0
	NEW_CONNECTION 		= 0x1
	EXISTING_CONNECTION	= 0x2
