'''
This module contains some constants that are used by the Bluetooth Low Energy stack.
'''

TYPE_HCI_COMMAND		= 0x1
TYPE_ACL_DATA 			= 0x2
TYPE_HCI_EVENT 			= 0x4

HCI_LE_META  			= 0x3e

HCI_CONNECTION_COMPLETE 	= 0x1
HCI_ADVERTISING_REPORT 		= 0x2
HCI_LONG_TERM_KEY_REQUEST	= 0x5
HCI_ENCRYPTION_CHANGE 		= 0x8
HCI_ENHANCED_CONNECTION_COMPLETE= 0xa

HCI_DISCONNECTION_COMPLETE 	= 0x5

ADV_IND 			= 0x0
ADV_DIRECT_IND			= 0x1
ADV_SCAN_IND 			= 0x2
ADV_NONCONN_IND 		= 0x3
SCAN_RSP			= 0x4
ADV_DIRECT_IND_LOW		= 0x4

# ATT Error Codes
ATT_ERR_INVALID_HANDLE		=	0x01
ATT_ERR_READ_NOT_PERMITTED   	=	0x02
ATT_ERR_WRITE_NOT_PERMITTED   	=	0x03
ATT_ERR_INVALID_PDU   		=	0x04
ATT_ERR_INSUFFICIENT_AUTHEN	=	0x05
ATT_ERR_UNSUPPORTED_REQ   	=	0x06
ATT_ERR_INVALID_OFFSET   	=	0x07
ATT_ERR_INSUFFICIENT_AUTHOR	=	0x08
ATT_ERR_PREPARE_QUEUE_FULL   	=	0x09
ATT_ERR_ATTR_NOT_FOUND		=	0x0a
ATT_ERR_ATTR_NOT_LONG   	=	0x0b
ATT_ERR_INSUFFICIENT_KEY_SIZE	=	0x0c
ATT_ERR_INVALID_VALUE_SIZE   	=	0x0d
ATT_ERR_UNLIKELY   		=	0x0e
ATT_ERR_INSUFFICIENT_ENCRYPT	=	0x0f
ATT_ERR_UNSUPPORTED_GRP_TYPE   	=	0x10
ATT_ERR_INSUFFICIENT_RESOURCES	=	0x11
ATT_ERR_INVALID_VALUE   	=	0x80

# SM Error Codes
SM_ERR_PASSKEY_ENTRY_FAILED	=	0x01
SM_ERR_OOB_NOT_AVAILABLE	=	0x02
SM_ERR_AUTH_REQUIREMENTS	=	0x03
SM_ERR_CONFIRM_VALUE_FAILED	=	0x04
SM_ERR_PAIRING_NOT_SUPPORTED	=	0x05
SM_ERR_ENCRYPTION_KEY_SIZE	=	0x06
SM_ERR_COMMAND_NOT_SUPPORTED	=	0x07
SM_ERR_UNSPECIFIED_REASON	=	0x08
SM_ERR_REPEATED_ATTEMPTS	=	0x09
SM_ERR_INVALID_PARAMETERS	=	0x0A
SM_ERR_DHKEY_CHECK_FAILED	=	0x0B
SM_ERR_NUMERIC_COMPARISON_FAILED=	0x0C
SM_ERR_BREDR_PAIRING_IN_PROGRESS=	0x0D
SM_ERR_CROSS_TRANSPORT_KEY	=	0x0E


CONTROL_TYPES = {
0x00 : "LL_CONNECTION_UPDATE_REQ",
0x01 : "LL_CHANNEL_MAP_REQ",
0x02 : "LL_TERMINATE_IND",
0x03 : "LL_ENC_REQ",
0x04 : "LL_ENC_RSP",
0x05 : "LL_START_ENC_REQ",
0x06 : "LL_START_ENC_RESP",
0x07 : "LL_UNKNOWN_RSP",
0x08 : "LL_FEATURE_REQ",
0x09 : "LL_FEATURE_RSP",
0x0A : "LL_PAUSE_ENC_REQ",
0x0B : "LL_PAUSE_ENC_RSP",
0x0C : "LL_VERSION_IND",
0x0D : "LL_REJECT_IND"
}

ADV_TYPES = {
0: "ADV_IND",
1: "ADV_DIRECT_IND",
2: "ADV_NONCONN_IND",
3: "SCAN_REQ",
4: "SCAN_RSP",
5: "CONNECT_REQ",
6: "ADV_SCAN_IND"
}

# Enumeration for operation mode
class BLEOperationMode:
	NORMAL 		= 0x0
	SCANNING 	= 0x1
	ADVERTISING 	= 0x2

# Enumeration for sniffing mode
class BLESniffingMode:
	ADVERTISEMENT		= 0x0
	NEW_CONNECTION 		= 0x1
	EXISTING_CONNECTION	= 0x2


# Control PDU opcodes supported by Zephyr RTOS
LLCTRL_TYPE_CONN_UPDATE_IND = 0x00
LLCTRL_TYPE_CHAN_MAP_IND = 0x01
LLCTRL_TYPE_TERMINATE_IND = 0x02
LLCTRL_TYPE_ENC_REQ = 0x03
LLCTRL_TYPE_ENC_RSP = 0x04
LLCTRL_TYPE_START_ENC_REQ = 0x05
LLCTRL_TYPE_START_ENC_RSP = 0x06
LLCTRL_TYPE_UNKNOWN_RSP = 0x07
LLCTRL_TYPE_FEATURE_REQ = 0x08
LLCTRL_TYPE_FEATURE_RSP = 0x09
LLCTRL_TYPE_PAUSE_ENC_REQ = 0x0A
LLCTRL_TYPE_PAUSE_ENC_RSP = 0x0B
LLCTRL_TYPE_VERSION_IND = 0x0C
LLCTRL_TYPE_REJECT_IND = 0x0D
LLCTRL_TYPE_SLAVE_FEATURE_REQ = 0x0E
LLCTRL_TYPE_CONN_PARAM_REQ = 0x0F
LLCTRL_TYPE_CONN_PARAM_RSP = 0x10
LLCTRL_TYPE_REJECT_EXT_IND = 0x11
LLCTRL_TYPE_PING_REQ = 0x12
LLCTRL_TYPE_PING_RSP = 0x13
LLCTRL_TYPE_LENGTH_REQ = 0x14
LLCTRL_TYPE_LENGTH_RSP = 0x15
LLCTRL_TYPE_PHY_REQ = 0x16
LLCTRL_TYPE_PHY_RSP = 0x17
LLCTRL_TYPE_PHY_UPD_IND = 0x18
LLCTRL_TYPE_MIN_USED_CHAN_IND = 0x19


# LL Controller Error Codes
LL_ERROR_CODES = {
    0x01: "UNKNOWN HCI COMMAND",
    0x02: "UNKNOWN CONNECTION IDENTIFIER",
    0x03: "HARDWARE FAILURE",
    0x04: "PAGE TIMEOUT",
    0x05: "AUTHENTICATION FAILURE",
    0x06: "PIN OR KEY MISSING",
    0x07: "MEMORY CAPACITY EXCEEDED",
    0x08: "CONNECTION TIMEOUT",
    0x09: "CONNECTION LIMIT EXCEEDED",
    0x0A: "SYNCHRONOUS CONNECTION LIMIT TO A DEVICE EXCEEDED",
    0x0B: "CONNECTION ALREADY EXISTS",
    0x0C: "COMMAND DISALLOWED",
    0x0D: "CONNECTION REJECTED DUE TO LIMITED RESOURCES",
    0x0E: "CONNECTION REJECTED DUE TO SECURITY REASONS",
    0x0F: "CONNECTION REJECTED DUE TO UNACCEPTABLE BD_ADDR",
    0x10: "CONNECTION ACCEPT TIMEOUT EXCEEDED",
    0x11: "UNSUPPORTED FEATURE OR PARAMETER VALUE",
    0x12: "INVALID HCI COMMAND PARAMETERS",
    0x13: "REMOTE USER TERMINATED CONNECTION",
    0x14: "REMOTE DEVICE TERMINATED CONNECTION DUE TO LOW RESOURCES",
    0x15: "REMOTE DEVICE TERMINATED CONNECTION DUE TO POWER OFF",
    0x16: "CONNECTION TERMINATED BY LOCAL HOST",
    0x17: "REPEATED ATTEMPTS",
    0x18: "PAIRING NOT ALLOWED",
    0x19: "UNKNOWN LMP PDU",
    0x1A: "UNSUPPORTED REMOTE FEATURE / UNSUPPORTED LMP FEATURE",
    0x1B: "SCO OFFSET REJECTED",
    0x1C: "SCO INTERVAL REJECTED",
    0x1D: "SCO AIR MODE REJECTED",
    0x1E: "INVALID LMP PARAMETERS / INVALID LL PARAMETERS",
    0x1F: "UNSPECIFIED ERROR",
    0x20: "UNSUPPORTED LMP PARAMETER VALUE / UNSUPPORTED LL PARAMETER VALUE",
    0x21: "ROLE CHANGE NOT ALLOWED",
    0x22: "LMP RESPONSE TIMEOUT / LL RESPONSE TIMEOUT",
    0x23: "LMP ERROR TRANSACTION COLLISION / LL PROCEDURE COLLISION",
    0x24: "LMP PDU NOT ALLOWED",
    0x25: "ENCRYPTION MODE NOT ACCEPTABLE",
    0x26: "LINK KEY CANNOT BE CHANGED",
    0x27: "REQUESTED QoS NOT SUPPORTED",
    0x28: "INSTANT PASSED",
    0x29: "PAIRING WITH UNIT KEY NOT SUPPORTED",
    0x2A: "DIFFERENT TRANSACTION COLLISION",
    0x2C: "QoS UNACCEPTABLE PARAMETER",
    0x2D: "QoS REJECTED",
    0x2E: "CHANNEL ASSESSMENT NOT SUPPORTED",
    0x2F: "INSUFFICIENT SECURITY",
    0x30: "PARAMETER OUT OF MANDATORY RANGE",
    0x32: "ROLE SWITCH PENDING",
    0x34: "RESERVED SLOT VIOLATION",
    0x35: "ROLE SWITCH FAILED",
    0x36: "EXTENDED INQUIRY RESPONSE TOO LARGE",
    0x37: "SIMPLE PAIRING NOT SUPPORTED BY HOST",
    0x38: "HOST BUSY–PAIRING",
    0x39: "CONNECTION REJECTED DUE TO NO SUITABLE CHANNEL FOUND",
    0x3A: "CONTROLLER BUSY",
    0x3B: "UNACCEPTABLE CONNECTION PARAMETERS",
    0x3C: "ADVERTISING TIMEOUT",
    0x3D: "CONNECTION TERMINATED DUE TO MIC FAILURE",
    0x3E: "CONNECTION FAILED TO BE ESTABLISHED / SYNCHRONIZATION TIMEOUT",
    0x3F: "MAC CONNECTION FAILED",
    0x40: "COARSE CLOCK ADJUSTMENT REJECTED BUT WILL TRY TO ADJUST USING CLOCK DRAGGING",
    0x41: "TYPE0 SUBMAP NOT DEFINED",
    0x42: "UNKNOWN ADVERTISING IDENTIFIER",
    0x43: "LIMIT REACHED",
    0x44: "OPERATION CANCELLED BY HOST",
    0x45: "PACKET TOO LONG",
}